import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  // SignOutButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  // UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import UserButtonWrapper from "./UserButtonWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignInUrl="/browse"
      afterSignUpUrl="/browse"
    >
      <html lang="en">
        <body className="antialiased">
          <header className="w-full bg-gray-200 px-6 py-3 shadow-sm">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <Link href="/browse" className="text-xl font-semibold">
                Browse Courses
              </Link>

              <div className="flex items-center gap-4 ml-auto">
                <SignedOut>
                  <div className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition">
                    <SignInButton></SignInButton>
                  </div>
                  {/* </SignInButton> */}
                  <div className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition">
                    <SignUpButton>Sign Up</SignUpButton>
                  </div>
                </SignedOut>

                <SignedIn>
                  <UserButtonWrapper />
                </SignedIn>
              </div>
            </div>
          </header>

          <main className="min-h-screen">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
