import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./(home)/_components/Header";
import { AppBar, Toolbar, Typography, TextField } from "@mui/material";
import SearchBar from "./(home)/_components/SearchBar";
import DynamicSearchBarWrapper from "./(home)/_components/DynamicSearchBarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header
            className="flex justify-end items-center p-4 gap-4 h-16 "
            style={{ backgroundColor: "#D3D3D3" }}
          >
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <DynamicSearchBarWrapper />
              <UserButton />
            </SignedIn>
          </header>
          {/* <SignedIn>
            <Header />
          </SignedIn> */}

          <SignedOut></SignedOut>

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
